// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzWXtUm_CAHan38yYmPjajhzkDGqiK8xg',
    appId: '1:306153153032:web:cc73a16efa30cae582e7bd',
    messagingSenderId: '306153153032',
    projectId: 'meet--zone',
    authDomain: 'meet--zone.firebaseapp.com',
    storageBucket: 'meet--zone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXmZ4YlIOswW6YBTqfLVC7j41RI4HBPdE',
    appId: '1:306153153032:android:784524edcd2f0d0482e7bd',
    messagingSenderId: '306153153032',
    projectId: 'meet--zone',
    storageBucket: 'meet--zone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMgJyeYTOCmqq7_Z2tdYhhL7ypfg2wWLo',
    appId: '1:306153153032:ios:06f66d93b04cb40582e7bd',
    messagingSenderId: '306153153032',
    projectId: 'meet--zone',
    storageBucket: 'meet--zone.appspot.com',
    androidClientId: '306153153032-05cea1nlsk21vrp42e9jtsd7pheo197p.apps.googleusercontent.com',
    iosClientId: '306153153032-cr1218deer35520gb5vkprdopned2sth.apps.googleusercontent.com',
    iosBundleId: 'com.example.online',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMgJyeYTOCmqq7_Z2tdYhhL7ypfg2wWLo',
    appId: '1:306153153032:ios:06f66d93b04cb40582e7bd',
    messagingSenderId: '306153153032',
    projectId: 'meet--zone',
    storageBucket: 'meet--zone.appspot.com',
    androidClientId: '306153153032-05cea1nlsk21vrp42e9jtsd7pheo197p.apps.googleusercontent.com',
    iosClientId: '306153153032-cr1218deer35520gb5vkprdopned2sth.apps.googleusercontent.com',
    iosBundleId: 'com.example.online',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzWXtUm_CAHan38yYmPjajhzkDGqiK8xg',
    appId: '1:306153153032:web:7950683d9e2022e682e7bd',
    messagingSenderId: '306153153032',
    projectId: 'meet--zone',
    authDomain: 'meet--zone.firebaseapp.com',
    storageBucket: 'meet--zone.appspot.com',
  );
}
